# Generated by Django 4.1 on 2022-10-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0008_landing_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelayananKonseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='-', max_length=30)),
                ('nama', models.CharField(default='-', max_length=30)),
                ('status_user', models.CharField(default='-', max_length=20)),
                ('noHP', models.CharField(max_length=12)),
                ('email', models.EmailField(default='-', max_length=50)),
                ('bentuk_konseling', models.CharField(default='-', max_length=30)),
                ('keluhan_konseling', models.TextField(default='-')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pelayananKonseling', to='landing.landing')),
            ],
        ),
        migrations.CreateModel(
            name='PreferensiWaktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagi', models.BooleanField(default=False)),
                ('siang', models.BooleanField(default=False)),
                ('sore', models.BooleanField(default=False)),
                ('malam', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferensiWaktu', to='pelayananKonseling.pelayanankonseling')),
            ],
        ),
        migrations.CreateModel(
            name='PreferensiHari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senin', models.BooleanField(default=False)),
                ('selasa', models.BooleanField(default=False)),
                ('rabu', models.BooleanField(default=False)),
                ('kamis', models.BooleanField(default=False)),
                ('jumat', models.BooleanField(default=False)),
                ('sabtu', models.BooleanField(default=False)),
                ('minggu', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferensiHari', to='pelayananKonseling.pelayanankonseling')),
            ],
        ),
    ]
