# Generated by Django 4.1 on 2022-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananKonseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='bentuk_konseling',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online via chat', 'Online via chat'), ('Online via video call', 'Online via video call')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='keluhan_konseling',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='nama',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='noHP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='status_user',
            field=models.CharField(choices=[('Mahasiswa UI', 'Mahasiswa UI'), ('Pegawai UI', 'Pegawai UI'), ('Others', 'Others')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
