# Generated by Django 4.1 on 2022-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananKonseling', '0002_alter_pelayanankonseling_bentuk_konseling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelayanankonseling',
            name='noHP',
            field=models.IntegerField(),
        ),
    ]
