# Generated by Django 4.1 on 2022-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananKonseling', '0003_alter_pelayanankonseling_nohp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelayanankonseling',
            name='status_konseling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
