# Generated by Django 4.1 on 2022-10-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananKonseling', '0004_pelayanankonseling_status_konseling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferensiwaktu',
            name='user',
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='jumat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='kamis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='malam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='minggu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='pagi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='rabu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='sabtu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='selasa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='senin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='siang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelayanankonseling',
            name='sore',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PreferensiHari',
        ),
        migrations.DeleteModel(
            name='PreferensiWaktu',
        ),
    ]
