# Generated by Django 4.1 on 2022-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananDokter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layan',
            name='statusObat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
