# Generated by Django 4.1 on 2022-10-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananDokter', '0002_alter_layan_dokter_alter_layan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='layan',
            name='username',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
