# Generated by Django 4.1 on 2022-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananDokter', '0003_layan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='layan',
            name='hasilPeriksa',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
