# Generated by Django 4.1 on 2022-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landing_is_admin_landing_is_apotek_landing_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='landing',
            name='is_apotek',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='landing',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
