# Generated by Django 4.1 on 2022-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_landing_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='doctorReady',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
