# Generated by Django 4.1 on 2022-10-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_landing_doctorready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='doctorReady',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
