# Generated by Django 4.1 on 2022-10-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0008_landing_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_user', to='landing.landing')),
            ],
        ),
    ]
