# Generated by Django 4.1 on 2022-10-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayar',
            name='keterangan',
            field=models.TextField(default='a'),
        ),
    ]
