# Generated by Django 4.1 on 2022-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0004_bayar_date_alter_bayar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayar',
            name='bulan',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='bayar',
            name='keterangan',
            field=models.TextField(),
        ),
    ]
