# Generated by Django 4.1 on 2022-11-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0005_bayar_bulan_alter_bayar_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayar',
            name='date',
        ),
    ]
