# Generated by Django 4.1 on 2022-10-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0008_landing_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=30)),
                ('jam', models.CharField(max_length=30)),
                ('keterangan', models.TextField()),
                ('dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_operasi', to='landing.landing')),
                ('pasien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasien_operasi', to='landing.landing')),
            ],
        ),
    ]
