# Generated by Django 4.1 on 2022-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasi',
            name='keterangan',
            field=models.CharField(max_length=1000),
        ),
    ]
