# Generated by Django 4.1 on 2022-10-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasi',
            name='dokter',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operasi',
            name='pasien',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
