# Generated by Django 4.1 on 2022-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0002_alter_operasi_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='operasi',
            name='usernameDokter',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='operasi',
            name='usernamePasien',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
