# Generated by Django 4.1 on 2022-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0003_alter_operasi_dokter_alter_operasi_pasien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operasi',
            name='durasi',
        ),
        migrations.RemoveField(
            model_name='operasi',
            name='jenis',
        ),
    ]
