# Generated by Django 4.1 on 2022-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasi', '0003_operasi_usernamedokter_operasi_usernamepasien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operasi',
            name='jam',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='operasi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
