# Generated by Django 4.1 on 2022-10-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananApotek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obat',
            name='kuantitas',
        ),
        migrations.AddField(
            model_name='obat',
            name='status_obat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
