# Generated by Django 4.1 on 2022-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayananApotek', '0002_remove_obat_kuantitas_obat_status_obat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='obat',
            name='harga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obat',
            name='nama_obat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
